#!/bin/sh

# chkconfig: 2345 90 30
# description: Say forever that Inna You is beautiful.


innasrv=/usr/local/sbin/innasrv
pidfile=/var/run/innasrv.pid
logfile=/var/log/innasrv.log

case $1 in
  start)
    $innasrv
    ;;
  stop)
    kill -TERM `cat $pidfile`
    ;;
  reload)
    kill -HUP `cat $pidfile`
    ;;
  restart)
    $0 stop
    sleep 1
    $0 start
    ;;
  monitor)
    tail -f $logfile
    ;;
  *)
    echo "usage: $0 { start | stop | reload | restart | monitor }"
    exit 0
esac
